[package]
name = "git-clone"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.40", features = ["derive"] }
flate2 = "1.1.2"
hex = "0.4.3"
sha1 = "0.10.6"
thiserror = "2.0.12"
